config/routes.rb
Flynride::Application.routes.draw do
  resources :users

  post "pairings/create"

  get "pairings/destroy"

  post "sms_incoming/examine"

  resources :riders
  resource :session, :only => [:new, :create]
  post "sessions/broadcast", to: "sessions#broadcast"
  
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :date, :flight_no, :id
  
  has_many :riders
end

app/models/pairing.rb
class Pairing < ActiveRecord::Base
  attr_accessible :id, :phone_virtual, :user1_id, :user2_id
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  attr_accessible :final_dest, :flight_id, :id, :user_id

  belongs_to :user
  belongs_to :flight
  
  
  def address_lists

    Rider.find_all_by_flight_id(self.flight_id).map do |rider|
      next if rider == self
      [self.user_id, self.final_dest]
    end

  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :phone_no, :token, :confirm_code

  has_many :riders
  
  def set_token
    self.token = SecureRandom.urlsafe_base64

  end
  
  def self.verify_credentials(phone_no, confirm_code)
    user = User.find_by_phone_no(phone_no)
    db_confirm_code = user.confirm_code
    
    user && db_confirm_code == confirm_code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery :except => [:examine]

  helper_method :session_exist?, :current_user, :current_rider


  def login(user)
    user.set_token
    session[:token] = user.token
    user.save!
  end
  
  def current_user
    session_token = session[:token]
    user = User.find_by_token(session_token)
    if session_token && user
      user
    else 
      nil
    end
  end

  def current_rider 
 	current_user.riders.first
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
end

app/controllers/geo_ranker_controller.rb
require 'google_directions'

class GeoRankerController < ApplicationController
  
 
end

app/controllers/pairings_controller.rb
require 'twilio-ruby'


class PairingsController < ApplicationController
  def create
  	@pairing = Pairing.new(params[:pairing])
  	@pairing.phone_virtual = "+19782527433"

  	@pairing_second = Pairing.new(user1_id:params[:pairing][:user2_id],user2_id:params[:pairing][:user1_id])
	@pairing_second.phone_virtual = "+19782527433"

  	account_sid = 'AC275d394d4f0465c8e0b6694216f29de2'
	auth_token = 'e17754e672ee9ef3b21fd5708aba4314'
	client = Twilio::REST::Client.new account_sid, auth_token

	client.account.sms.messages.create(
    	:from => @pairing.phone_virtual,
    	:to => User.find_by_id(@pairing.user1_id).phone_no,
    	:body => "Use this anonymous number to contact your FlyNRide companion "
	)

	client.account.sms.messages.create(
    	:from => @pairing.phone_virtual,
    	:to => User.find_by_id(@pairing_second.user1_id).phone_no,
    	:body => "Use this anonymous number to correspond with a FlyNRide user that want to meet"
	)

  	if @pairing.save && @pairing_second.save
		render :json => @pairing
  	else
  		render :json => @pairing.errors.full_messages, :status => 422
  	end

  end

  def destroy
  end
end

app/controllers/riders_controller.rb
require 'google_directions'

class RidersController < ApplicationController
  
  def compute_distance (origin, destination)
    directions = GoogleDirections.new(origin, destination)
    logger.debug directions.distance_in_miles
    
    return directions.distance_in_miles, directions.status
  end

  def rank_distances  
    distances = Array.new

    Rider.find_all_by_flight_id(current_rider.flight_id).map do |rider|
      next if rider == current_rider
      computed_distance, status = compute_distance(rider.final_dest, current_rider.final_dest)

      if status != "NOT_FOUND"
        distances << {:id=>rider.id, :distance=>computed_distance, :final_dest=>rider.final_dest}
      end         
    end

    return distances.sort_by {|a| a[:distance]}
  end


  def index
    @rank_results = rank_distances    
  #  render :json => @rank_results

    p @rank_results
    render :index
  end
  
  def new
    if current_user
      @rider = current_user.riders.first || Rider.new(:user_id => current_user.id)
    else
      @rider = Rider.new
    end
    
    render :new
  end
  
  def update
    current_rider = Rider.find_by_id(params[:id])
    current_rider.update_attributes(params[:rider])
    
    current_flight = Flight.find_by_flight_no_and_date(params[:flight][:flight_no],params[:flight][:date]) || Flight.new(params[:flight])
    current_flight.save!
    
    current_rider.flight_id = current_flight.id
    
    current_rider.save!
    
    redirect_to riders_url
  end
  
  def create
    
  
  end
  
  def destroy
    
  end
  
end

app/controllers/sessions_controller.rb
require 'twilio-ruby'

#development 
# account_sid = 'AC66be6b0404db8bc0c5e1ea7aeeab1cde'
# auth_token = 'fd54aa7b10d8e1660f15e104302f2c17'

#production 
account_sid = 'AC275d394d4f0465c8e0b6694216f29de2'
auth_token = 'e17754e672ee9ef3b21fd5708aba4314'


class SessionsController < ApplicationController
  def new
    render :new
  end
  
  def broadcast
    account_sid = 'AC275d394d4f0465c8e0b6694216f29de2'
    auth_token = 'e17754e672ee9ef3b21fd5708aba4314'
    client = Twilio::REST::Client.new account_sid, auth_token
    
    confirm_code = SecureRandom.random_number(10000).to_s
    phone_num = params[:phone_num]
    
    user = User.find_by_phone_no(phone_num) || User.new(:phone_no => phone_num)
    
    user.confirm_code = confirm_code
    user.save!
    
    client.account.sms.messages.create(
        :from => "+19782527433",
        :to => phone_num,
        :body => confirm_code
    )
    
    render :json => "success"
  end
  
  def create
    phone_num = params[:phone_num]
    confirm_code = params[:confirmCode]

    if User.verify_credentials(phone_num, confirm_code)
      user = User.find_by_phone_no(phone_num)
      login(user)
      @rider = user.riders.first || Rider.new(user_id: user.id)
      @rider.save!
      redirect_to new_rider_url
    else
      redirect_to new_session_url
    end
    
  end

end

app/controllers/sms_incoming_controller.rb
require 'twilio-ruby'

#development 
#account_sid = 'AC66be6b0404db8bc0c5e1ea7aeeab1cde'
#auth_token = 'fd54aa7b10d8e1660f15e104302f2c17'

#production 
account_sid = 'AC275d394d4f0465c8e0b6694216f29de2'
auth_token = 'e17754e672ee9ef3b21fd5708aba4314'


class SmsIncomingController < ApplicationController
  def examine
  	@input_number  = params[:From]
  	@input_message = params[:Body] 
 	logger.debug "from: #{@input_number} message:#{@input_message}"

 	@from_user =User.find_by_phone_no(@input_number)

 	@pairing = Pairing.find_by_user1_id(@from_user.id)

	@to_user = User.find_by_id(@pairing.user2_id)

 	twiml = Twilio::TwiML::Response.new do |r|
    	r.Sms "#{@input_message}", :from => @pairing.phone_virtual, :to => @to_user.phone_no
  	end
  	
  	logger.debug "#{twiml.text}"

  	respond_to do |format|	
  		format.xml {render xml: twiml.text}
 	end 


  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/geo_ranker_helper.rb
module GeoRankerHelper
end

app/helpers/pairings_helper.rb
module PairingsHelper
end

app/helpers/riders_helper.rb
module RidersHelper

	def generateMapUrl(rankResults) 
		@colors = ["black","blue","red","green"]
		@base_map_url = "http://maps.googleapis.com/maps/api/staticmap?sensor=false&size=900x300&maptype=roadmap&"

		@base_map_url += "markers=color:#{@colors[0]}|label:You|#{current_rider.final_dest}&"


		rankResults.each_with_index  do |result, idx|

			@base_map_url += "markers=color:#{@colors[idx+1]}|label:#{(idx + 97).chr.capitalize}|#{result[:final_dest]}&"
			
			break if idx == 2 

		end

		@base_map_url
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sms_incoming_helper.rb
module SmsIncomingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/geo_ranker/compute_distance.html.erb
<h1>GeoRanker#compute_distance</h1>
<p>Find me in app/views/geo_ranker/compute_distance.html.erb</p>

app/views/geo_ranker/rank_distances.html.erb
<h1>GeoRanker#rank_distances</h1>
<p>Find me in app/views/geo_ranker/rank_distances.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fly'n'Ride</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:700,400" rel="stylesheet" type="text/css">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pairings/create.html.erb
<h1>Pairings#create</h1>
<p>Find me in app/views/pairings/create.html.erb</p>

app/views/pairings/destroy.html.erb
<h1>Pairings#destroy</h1>
<p>Find me in app/views/pairings/destroy.html.erb</p>

app/views/riders/index.html.erb
<nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <a class="navbar-brand" id="header-logo" href="#">Fly'n'Ride</a>
        <a class="navbar-brand" href="#" id="view-match-link">View Matches</a>
        <a class="navbar-brand" href="<%= new_rider_url %>" id="edit-ride">Edit Ride</a>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12 intro">
          <h3>We've found some matches for you!</h3>
          <p>Matched riders are sorted by proximity of final destination. Start messaging now and save some cab money!<br>
          <span class="small-text">* Fees may apply based on cellphone carriers.</span></p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12" id="ridermap">
          <img src="<%=generateMapUrl(@rank_results)%>">
        </div>

        <div class="col-sm-12">
          
        <% @rank_results.each_with_index do |result, idx| %>
          <div class="col-sm-4">
            <div class="panel panel-default">  
            
              <div class="panel-heading"><%= (idx + 97).chr.capitalize %>: <%= result[:distance] %> miles from your destination</div>
              <div class="panel-body">
                <address><%=link_to result[:final_dest],"https://www.google.com/local?q=#{result[:final_dest]}" %></address>
              </div>

              <form class="pair">
                  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  
                  <input name="pairing[user1_id]" type="hidden" value="<%= current_user.id %>">
                  <input name="pairing[user2_id]" type="hidden" value="<%= result[:id] %>">

                  <button class="pairButton btn btn-small sendsms" data-loading-text="Contacted">SMS</button>
              </form>
              
            </div>
          </div>
        <% end %>

        </div> <!-- End of 12 Columns -->
      </div> <!-- End of Row -->
    </div> <!-- End of Container -->





    <script>
      $("form.pair").on("submit", function (event) {
          event.preventDefault();
          
          $(event.target.lastElementChild).html("<span class='glyphicon glyphicon-ok'></span> Contacted");
          $(event.target.lastElementChild)  .attr("disabled", "disabled");
          var formData = $(this).serialize();
          $.ajax({
            url: "/pairings/create",
            type: "POST",
            data: formData,
            success: function () {
              console.log("submited!!!");
            }
          });
        }
      );
    </script>

app/views/riders/new.html.erb
<% if @rider.id %>
	<% action_url = rider_url(@rider)%>
<% else %>
	<% action_url = riders_url %>
<%end%>

<% flight_no = @rider.flight.flight_no if @rider.flight %>
<% flight_date = @rider.flight.date if @rider.flight %>
<% phone_no = current_user.phone_no if current_user %>

<nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <a class="navbar-brand" id="header-logo" href="#">Fly'n'Ride</a>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12 intro">
            <h3>Enter your flight info here:</h3>
            <p>Tell us about your flight information and where your are going. We will match you up with relevant fellow travelers on your flight.<br>
        </div>
      </div> <!-- End of Row -->

      <div class="row">
        <form action="<%= action_url %>" method="post" class="col-md-12" role="form">

          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
          
          <% if @rider.user_id %>
            <input type="hidden" name="_method" value="put" />
            <input name="rider[user_id]" type="hidden" value="<%= @rider.user_id %>">
          <% end %>
          
          <div class="row">
              <div class="col-sm-6 form-group">
                <label for="flightno">Flight No.</label>
                <input type="text" value="<%= flight_no %>" name="flight[flight_no]" class="form-control" id="flightno" placeholder="Enter Flight No." required>
              </div>
              
              <div class="col-sm-6 form-group">
                <label for="date">Date</label>
                <input type="date" value="<%= flight_date %>" name="flight[date]" class="form-control" id="date" placeholder="Enter Flight Date" required>

              </div>
          </div>
          <div class="row">
            <div class="col-sm-12 form-group">
              <label for="destination">Final Destination</label>
              <input type="text" value="<%= @rider.final_dest %>" name="rider[final_dest]" class="form-control" id="destination" placeholder="Final Destination" required>
            </div>
          </div>
          
          <button type="submit" class="btn add-bottom">Find Other Riders</button>
        </form>
      </div> <!-- End of Row -->
    </div> <!-- End of Container -->
</div>

app/views/riders/new.index.erb
<nav class="navbar navbar-default" role="navigation">
  <h1>Matches</h1>
  <span>Account</span>
</nav>
<div class="container">
  <div>
    Matched riders are sorted by proximity of final destination. Start messaging now and save some cab money!
    <span>Fees may apply based on cellphone carriers.</span>
  </div>
  <div>
    <div class="panel panel-default">
      <div class="panel-heading">Rider A</div>
      <div class="panel-body">
        <address>Abc St. &#038; Def St., City Name, ST 123456</address>
      </div>
      <div class="panel-footer"><button class="btn btn-primary">Message!</button></div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Rider B</div>
      <div class="panel-body">
        <address>Abc St. &#038; Def St., City Name, ST 123456</address>
      </div>
      <div class="panel-footer"><button class="btn btn-primary">Message!</button></div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">Rider C</div>
      <div class="panel-body">
        <address>Abc St. &#038; Def St., City Name, ST 123456</address>
      </div>
      <div class="panel-footer"><button class="btn btn-primary">Message!</button></div>
    </div>
  </div>
</div>

app/views/sms_incoming/examine.html.erb
<h1>SmsIncoming#examine</h1>
<p>Find me in app/views/sms_incoming/examine.html.erb</p>